### ISSUE TITLE
Botones

### ISSUE THREAD

**Issue by aranzabe** [aranzabe/AndroidDAM2_22_23#2]

**Comment by CrisJaP** [comment]
Jeloudah!

**Comment by Adry18** [comment]
Hola

**Comment by Alfreditto** [comment]
![92330765](https://user-images.githubusercontent.com/92330765/194266827-42999510-75eb-4493-939a-fcdc811c3469.jpg)

**Comment by aranzabe** [comment]
Como se ha entendido. Pasamos de panatalla.
